#!/bin/bash

#First remove the event files
sudo rm /dbfs/tmp/gdelt/latest_gdelt_events.csv
sudo rm /dbfs/tmp/gdelt/latest_gdelt_events.csv.zip
sudo rm /dbfs/tmp/gdelt/latest_gdelt_mentions.csv
sudo rm /dbfs/tmp/gdelt/latest_gdelt_mentions.csv.zip

#Get url towards latest GDELT EVENTS update
get_gdelt_zip_url() {
    content=$(curl -v --silent http://data.gdeltproject.org/gdeltv2/lastupdate.txt --stderr - | grep $1)
    IFS=' ' read -a content_components <<< "$content"
    latest_gdelt_url="${content_components[2]}"
    IFS='/' read -a url_components <<< "$latest_gdelt_url"
    compressed_file_name="${url_components[4]}"
    IFS='.' read -a file_components <<< "$compressed_file_name"
    csv_file_name="${file_components[0]}.${file_components[1]}.${file_components[2]}"
}

# ----------- Get url towards latest GDELT EVENTS update -----------
$EVENTS="export.CSV.zip"
get_gdelt_zip_url() $EVENTS
curl $latest_gdelt_url > /dbfs/tmp/gdelt/latest_gdelt_events.csv.zip
unzip -p "/dbfs/tmp/gdelt/latest_gdelt_events.csv.zip" $csv_file_name > /dbfs/tmp/gdelt/latest_gdelt_events.csv

# ----------- Get url towards latest GDELT EVENTS update -----------
$MENTIONS="mentions.CSV.zip"
get_gdelt_zip_url() $MENTIONS
curl $latest_gdelt_url > /dbfs/tmp/gdelt/latest_gdelt_mentions.csv.zip
unzip -p "/dbfs/tmp/gdelt/latest_gdelt_events.csv.zip" $csv_file_name > /dbfs/tmp/gdelt/latest_gdelt_events.csv
